### ISSUE TITLE
Potential build limitation due to Docker Hub

### ISSUE THREAD

**Issue by ghost** [Dexels/dexels-base#1]
We received the following e-mail from CircleCI, and we need to investigate whether and how this will affect us.

> Hi there, 
> 
> On November 1st, Docker Hub will begin limiting anonymous image pulls. We want to make sure you know how you might be impacted and what you can do to avoid interruptions to your workflow. 
> 
> Adding Docker authentication to your pipeline config is the easiest way to avoid any service disruptions. If you use the Docker executor or pull Docker images when using the machine executor on CircleCI, we encourage you to authenticate. Because the anonymous API rate limits are based on IP addresses, they will impact CircleCI cloud customers. Authenticated users get higher per-user rate limits, regardless of IP. 
> 
> We are currently working on a partnership with Docker to minimize the impact of this change for our users and will share more details as we get them. 
> 
> For more information or to leave a question for us, please head over to Discuss or contact support. 
> 
> Thanks and happy building, 
> 
> - The CircleCI team

**Comment by ghost** [comment]
Additional info ...

- [DockerHub rate limiting FAQ](https://support.circleci.com/hc/en-us/articles/360050623311-Docker-Hub-rate-limiting-FAQ).
- [Authenticate with Docker](https://discuss.circleci.com/t/authenticate-with-docker-to-avoid-impact-of-nov-1st-rate-limits/37567).

**Comment by jrtaal** [comment]
Proposed steps:

1. Create a context in CCI: (Context share sensitive information over all projects)
```
dexels_docker_hub:
- DOCKERHUB_USER: jkdsfhjkds
- DOCKERHUB_PASS: sdfjsldkf
```
2. Allow workflows to access shared credentials
```
workflows:
  version: 2
  workflow:
    jobs:
      - targetplatform:
        context:
        - dexels_docker_hub
      - build:
        context:
        - dexels_docker_hub
      - package:
        context:
        - dexels_docker_hub
        requires:
        - build
```

3. Use credentials:
```
jobs:
  targetplatform:
    docker:
      - image: circleci/openjdk:11-jdk
        auth:
          username: $DOCKERHUB_USER  # can specify string literal values
          password: $DOCKERHUB_PASS  # or project environment variable reference
...
       - run
         docker login -u $DOCKERHUB_USER -p $DOCKERHUB_PASS
```
